# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK

# Production:
# secret_key_base: def0a2e9b5a4ff1149483abec1f5498d85e06124d9f6ec6398cfffd295627338761d52dd8ac6fe6274d67ab245407bc740b4436cf79d408a5c494d50d27676d3
# twitter_consumer_key: "TWObcmr7c5cOhvyLAgEBfy2Cd"
# twitter_consumer_secret: "5L7ePUkWsb5lRFv9pPLoJCcEodjhPQrASsJdGr7XdcEMfCOqEE"
# twitter_access_token: "2748660599-vxGussjx6LF85YWQUWa5pRSuU0s6N6xwCS3Gio5"
# twitter_access_token_secret: "Ih2e9Ezow9JQ7IoGpQgxhJO4A3iPYyOFPunTlyKLXxhwH"
# yahoo_consumer_key: "dj0yJmk9OEMzb2FaeHlVSmpBJmQ9WVdrOVdWSmtTMlJtTlRJbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kYw--"
# yahoo_consumer_secret: "35caae4a642a9a0a62fc0e41e7ac1535785e945a"


# Test:
secret_key_base: def0a2e9b5a4ff1149483abec1f5498d85e06124d9f6ec6398cfffd295627338761d52dd8ac6fe6274d67ab245407bc740b4436cf79d408a5c494d50d27676d3
twitter_consumer_key: "2TtN91nMhago6nNLdeO5eHdWw"
twitter_consumer_secret: "9AXJrjfQ0bMMit4vRkxNZKIalCIbUccGysmwreoQq1sZnIIGQa"
twitter_access_token: "2748660599-BEPTakDT8qm4guyHaEXP2jSFt4IAeBqPkxKbyVD"
twitter_access_token_secret: "dZdRsCwGB3OOsxY6dYwJPaRKHfbmZkPhhl9RDCYLHb08j"
yahoo_consumer_key: "dj0yJmk9OEMzb2FaeHlVSmpBJmQ9WVdrOVdWSmtTMlJtTlRJbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kYw--"
yahoo_consumer_secret: "35caae4a642a9a0a62fc0e41e7ac1535785e945a"